/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.coconutcode.infrastructure.persistence.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Sale extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4293091541297949461L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Sale\",\"namespace\":\"com.coconutcode.infrastructure.persistence.model\",\"fields\":[{\"name\":\"productId\",\"type\":\"string\"},{\"name\":\"productCategory\",\"type\":{\"type\":\"enum\",\"name\":\"ProductCategory\",\"symbols\":[\"GARDEN\",\"KITCHEN\",\"COOKING\",\"FOOD\",\"DRINK\",\"SPORT\",\"FASHION\",\"FURNITURE\"]}},{\"name\":\"saleDate\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Sale> ENCODER =
      new BinaryMessageEncoder<Sale>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Sale> DECODER =
      new BinaryMessageDecoder<Sale>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Sale> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Sale> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Sale>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Sale to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Sale from a ByteBuffer. */
  public static Sale fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence productId;
  @Deprecated public com.coconutcode.infrastructure.persistence.model.ProductCategory productCategory;
  @Deprecated public long saleDate;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Sale() {}

  /**
   * All-args constructor.
   * @param productId The new value for productId
   * @param productCategory The new value for productCategory
   * @param saleDate The new value for saleDate
   */
  public Sale(java.lang.CharSequence productId, com.coconutcode.infrastructure.persistence.model.ProductCategory productCategory, java.lang.Long saleDate) {
    this.productId = productId;
    this.productCategory = productCategory;
    this.saleDate = saleDate;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return productId;
    case 1: return productCategory;
    case 2: return saleDate;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: productId = (java.lang.CharSequence)value$; break;
    case 1: productCategory = (com.coconutcode.infrastructure.persistence.model.ProductCategory)value$; break;
    case 2: saleDate = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'productId' field.
   * @return The value of the 'productId' field.
   */
  public java.lang.CharSequence getProductId() {
    return productId;
  }

  /**
   * Sets the value of the 'productId' field.
   * @param value the value to set.
   */
  public void setProductId(java.lang.CharSequence value) {
    this.productId = value;
  }

  /**
   * Gets the value of the 'productCategory' field.
   * @return The value of the 'productCategory' field.
   */
  public com.coconutcode.infrastructure.persistence.model.ProductCategory getProductCategory() {
    return productCategory;
  }

  /**
   * Sets the value of the 'productCategory' field.
   * @param value the value to set.
   */
  public void setProductCategory(com.coconutcode.infrastructure.persistence.model.ProductCategory value) {
    this.productCategory = value;
  }

  /**
   * Gets the value of the 'saleDate' field.
   * @return The value of the 'saleDate' field.
   */
  public java.lang.Long getSaleDate() {
    return saleDate;
  }

  /**
   * Sets the value of the 'saleDate' field.
   * @param value the value to set.
   */
  public void setSaleDate(java.lang.Long value) {
    this.saleDate = value;
  }

  /**
   * Creates a new Sale RecordBuilder.
   * @return A new Sale RecordBuilder
   */
  public static com.coconutcode.infrastructure.persistence.model.Sale.Builder newBuilder() {
    return new com.coconutcode.infrastructure.persistence.model.Sale.Builder();
  }

  /**
   * Creates a new Sale RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Sale RecordBuilder
   */
  public static com.coconutcode.infrastructure.persistence.model.Sale.Builder newBuilder(com.coconutcode.infrastructure.persistence.model.Sale.Builder other) {
    return new com.coconutcode.infrastructure.persistence.model.Sale.Builder(other);
  }

  /**
   * Creates a new Sale RecordBuilder by copying an existing Sale instance.
   * @param other The existing instance to copy.
   * @return A new Sale RecordBuilder
   */
  public static com.coconutcode.infrastructure.persistence.model.Sale.Builder newBuilder(com.coconutcode.infrastructure.persistence.model.Sale other) {
    return new com.coconutcode.infrastructure.persistence.model.Sale.Builder(other);
  }

  /**
   * RecordBuilder for Sale instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Sale>
    implements org.apache.avro.data.RecordBuilder<Sale> {

    private java.lang.CharSequence productId;
    private com.coconutcode.infrastructure.persistence.model.ProductCategory productCategory;
    private long saleDate;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.coconutcode.infrastructure.persistence.model.Sale.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.productId)) {
        this.productId = data().deepCopy(fields()[0].schema(), other.productId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.productCategory)) {
        this.productCategory = data().deepCopy(fields()[1].schema(), other.productCategory);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.saleDate)) {
        this.saleDate = data().deepCopy(fields()[2].schema(), other.saleDate);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Sale instance
     * @param other The existing instance to copy.
     */
    private Builder(com.coconutcode.infrastructure.persistence.model.Sale other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.productId)) {
        this.productId = data().deepCopy(fields()[0].schema(), other.productId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.productCategory)) {
        this.productCategory = data().deepCopy(fields()[1].schema(), other.productCategory);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.saleDate)) {
        this.saleDate = data().deepCopy(fields()[2].schema(), other.saleDate);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'productId' field.
      * @return The value.
      */
    public java.lang.CharSequence getProductId() {
      return productId;
    }

    /**
      * Sets the value of the 'productId' field.
      * @param value The value of 'productId'.
      * @return This builder.
      */
    public com.coconutcode.infrastructure.persistence.model.Sale.Builder setProductId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.productId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'productId' field has been set.
      * @return True if the 'productId' field has been set, false otherwise.
      */
    public boolean hasProductId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'productId' field.
      * @return This builder.
      */
    public com.coconutcode.infrastructure.persistence.model.Sale.Builder clearProductId() {
      productId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'productCategory' field.
      * @return The value.
      */
    public com.coconutcode.infrastructure.persistence.model.ProductCategory getProductCategory() {
      return productCategory;
    }

    /**
      * Sets the value of the 'productCategory' field.
      * @param value The value of 'productCategory'.
      * @return This builder.
      */
    public com.coconutcode.infrastructure.persistence.model.Sale.Builder setProductCategory(com.coconutcode.infrastructure.persistence.model.ProductCategory value) {
      validate(fields()[1], value);
      this.productCategory = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'productCategory' field has been set.
      * @return True if the 'productCategory' field has been set, false otherwise.
      */
    public boolean hasProductCategory() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'productCategory' field.
      * @return This builder.
      */
    public com.coconutcode.infrastructure.persistence.model.Sale.Builder clearProductCategory() {
      productCategory = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'saleDate' field.
      * @return The value.
      */
    public java.lang.Long getSaleDate() {
      return saleDate;
    }

    /**
      * Sets the value of the 'saleDate' field.
      * @param value The value of 'saleDate'.
      * @return This builder.
      */
    public com.coconutcode.infrastructure.persistence.model.Sale.Builder setSaleDate(long value) {
      validate(fields()[2], value);
      this.saleDate = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'saleDate' field has been set.
      * @return True if the 'saleDate' field has been set, false otherwise.
      */
    public boolean hasSaleDate() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'saleDate' field.
      * @return This builder.
      */
    public com.coconutcode.infrastructure.persistence.model.Sale.Builder clearSaleDate() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Sale build() {
      try {
        Sale record = new Sale();
        record.productId = fieldSetFlags()[0] ? this.productId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.productCategory = fieldSetFlags()[1] ? this.productCategory : (com.coconutcode.infrastructure.persistence.model.ProductCategory) defaultValue(fields()[1]);
        record.saleDate = fieldSetFlags()[2] ? this.saleDate : (java.lang.Long) defaultValue(fields()[2]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Sale>
    WRITER$ = (org.apache.avro.io.DatumWriter<Sale>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Sale>
    READER$ = (org.apache.avro.io.DatumReader<Sale>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
