/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.coconutcode.salesbatchservice.infrastructure.persistence.model;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum ProductCategory {
  GARDEN, KITCHEN, COOKING, FOOD, DRINK, SPORT, FASHION, FURNITURE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ProductCategory\",\"namespace\":\"com.coconutcode.salesbatchservice.infrastructure.persistence.model\",\"symbols\":[\"GARDEN\",\"KITCHEN\",\"COOKING\",\"FOOD\",\"DRINK\",\"SPORT\",\"FASHION\",\"FURNITURE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
